# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdcaWWApK2AAZpb7aZTyOhVSlLrYPkLl
"""

import matplotlib.pyplot as plt
import numpy as np


x = np.linspace(0, 10, 200)
y = np.sin(x)


fig, ax = plt.subplots()
ax.plot(x, y, label="Sinus(x)", color="blue")


ax.set_title("Sinus Funksiyasining Grafiki")
ax.set_xlabel("X qiymatlari")
ax.set_ylabel("Y qiymatlari")


ax.grid(True)


ax.legend()


plt.show()

import matplotlib.pyplot as plt
import numpy as np


x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)

fig, ax = plt.subplots()
ax.scatter(x, y, color="blue", label="Nuqtalar", edgecolor="black")

ax.set_title("Tasodifiy Nuqtalar Scatter Grafiki")
ax.set_xlabel("X qiymatlari")
ax.set_ylabel("Y qiymatlari")


ax.grid(True)


ax.legend()


plt.show()